# Generated by Django 3.2.6 on 2021-08-03 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'price categories',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_description', models.CharField(help_text='Short internal description for users.', max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(help_text='Promotional material, can contain html code.', max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/upload')),
                ('active', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestra_season.season')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date and time of performance')),
                ('seats', models.IntegerField(help_text='Number of seats')),
                ('active', models.BooleanField(default=True)),
                ('open_sales', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start ticket sales')),
                ('close_transfer_sales', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Close transfer payment method')),
                ('close_sales', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Close ticket sales')),
                ('close_paper_sales', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Close paper sales (by members)')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orchestra_season.location')),
                ('price_categories', models.ManyToManyField(to='orchestra_season.PriceCategory')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='orchestra_season.production')),
            ],
        ),
    ]
