# Generated by Django 3.2.6 on 2021-08-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_season', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
