# Generated by Django 3.2.6 on 2021-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_season', '0002_alter_production_name_squashed_0007_auto_20210810_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hash',
            field=models.CharField(max_length=128),
        ),
    ]
