# Generated by Django 3.2.6 on 2021-09-26 15:38

from django.db import migrations, models
import orchestra_ticketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0003_alter_order_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=orchestra_ticketing.models.random_key, max_length=18),
        ),
        migrations.AddField(
            model_name='ticket',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
