# Generated by Django 3.2.6 on 2021-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0004_add_fields_for_scanning'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='language',
            field=models.CharField(default='nl', max_length=5),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'By bank transfer'), ('cash', 'At the register (using bancontact or payconic)')], default='cash', max_length=8),
        ),
    ]
