# Generated by Django 3.2.6 on 2021-10-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0005_add_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'By bank transfer'), ('cash', 'At the register (using bancontact or payconic)')], default='transfer', max_length=8),
        ),
    ]
