# Generated by Django 4.0.3 on 2022-04-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0009_pricecategory_name_en_pricecategory_name_nl'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='description_en',
            field=models.CharField(help_text='Promotional material, can contain html code.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='description_nl',
            field=models.CharField(help_text='Promotional material, can contain html code.', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='production',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
