# Generated by Django 4.2.2 on 2024-03-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0010_production_description_en_production_description_nl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_payment_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='not pay.nl', max_length=20),
            preserve_default=False,
        ),
    ]
