# Generated by Django 5.0.4 on 2024-04-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orchestra_ticketing",
            "0010_production_description_en_production_description_nl_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperorder",
            name="paid",
        ),
    ]
