# Generated by Django 5.0.4 on 2024-04-06 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestra_ticketing", "0011_remove_paid_paperorder"),
        (
            "payments",
            "0001_initial_squashed_0005_remove_payment_paid_alter_paypayment_payment_method_and_more_squashed_0006_alter_paypayment_pay_order_id",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payed",
            new_name="paid",
        ),
        migrations.RemoveField(
            model_name="performance",
            name="close_transfer_sales",
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.payment",
            ),
        ),
    ]
