# Generated by Django 4.1.7 on 2023-04-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0011_remove_pricecategory_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='allow_newsletter',
        ),
    ]
