# Generated by Django 4.2.2 on 2024-03-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0011_order_pay_payment_id_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='pay_payment_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='payment_status',
            field=models.CharField(default='not pay.nl', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
