# Generated by Django 4.2.2 on 2024-03-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0012_remove_order_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='pay_payment_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
