# Generated by Django 5.0.4 on 2024-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestra_ticketing", "0012_remove_order_allow_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="static/concert"),
        ),
    ]
