# Generated by Django 5.0.4 on 2024-04-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0012_rename_payed_order_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='accepted_conditions',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
