# Generated by Django 4.2.2 on 2024-03-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0013_alter_onlineorder_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='pay_payment_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
