# Generated by Django 6.0.3 on 2026-03-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orchestra_ticketing", "0013_production_pdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onlineorder",
            old_name="marketing_feedback",
            new_name="marketing_feedback_extra",
        ),
    ]
