# Generated by Django 5.1.2 on 2025-09-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0013_onlineorder_accepted_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
