# Generated by Django 6.0.3 on 2026-03-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orchestra_ticketing",
            "0014_rename_marketing_feedback_onlineorder_marketing_feedback_extra",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineorder",
            name="marketing_feedback",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muzikant", "Een muzikant/lid van het orkest"),
                    ("flyer", "Flyer/affiche"),
                    ("dans_leuven", "Dansschool Leuven"),
                    ("dans_herent", "Dansschool Herent"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("andere", "Andere..."),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
