# Generated by Django 4.2.2 on 2024-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0014_alter_onlineorder_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='pay_payment_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
