# Generated by Django 5.1.7 on 2026-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestra_ticketing", "0015_onlineorder_marketing_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineorder",
            name="marketing_feedback",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muzikant", "A musician/member of the orchestra"),
                    ("flyer", "Flyer/affiche"),
                    ("dans_leuven", "Dance school Leuven"),
                    ("dans_herent", "Dance school Herent"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("nieuwsbrief", "Our newsletter"),
                    ("andere", "Other..."),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
