# Generated by Django 4.2.2 on 2024-03-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra_ticketing', '0015_alter_onlineorder_pay_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineorder',
            old_name='pay_payment_id',
            new_name='pay_payment_id',
        ),
    ]
