# Generated by Django 5.1.7 on 2026-10-05 11:55

import django.db.models.deletion
from django.db import migrations, models


def migrate_marketing_choices(apps, schema_editor):
    MarketingChoice = apps.get_model("orchestra_ticketing", "MarketingChoice")
    OnlineOrder = apps.get_model("orchestra_ticketing", "OnlineOrder")
    database = schema_editor.connection.alias
    choices = [
        ("muzikant", "A musician/member of the orchestra",
         "Een muzikant/lid van het orkest"),
        ("flyer", "Flyer/affiche", "Flyer/affiche"),
        ("dans_leuven", "Dance school Leuven", "Dansschool Leuven"),
        ("dans_herent", "Dance school Herent", "Dansschool Herent"),
        ("instagram", "Instagram", "Instagram"),
        ("facebook", "Facebook", "Facebook"),
        ("nieuwsbrief", "Our newsletter", "Onze nieuwsbrief"),
        ("andere", "Other...", "Andere..."),
    ]
    for tag, text, translation in choices:
        MarketingChoice.objects.using(database).create(
            tag=tag, text=text, translation=translation
        )

    # Preserve legacy values not covered by the last static choices, too.
    existing_tags = set(tag for tag, _, _ in choices)
    stored_tags = OnlineOrder.objects.using(database).exclude(
        marketing_feedback__isnull=True
    ).values_list("marketing_feedback", flat=True).distinct()
    for tag in stored_tags:
        if tag not in existing_tags:
            MarketingChoice.objects.using(database).create(
                tag=tag, text=tag, translation=tag
            )


def assign_marketing_choices(apps, schema_editor):
    Production = apps.get_model("orchestra_ticketing", "Production")
    MarketingChoice = apps.get_model("orchestra_ticketing", "MarketingChoice")
    database = schema_editor.connection.alias
    choices = list(
        MarketingChoice.objects.using(database)
    )
    for production in Production.objects.using(database).iterator():
        production.marketing_choices.add(*choices)


class Migration(migrations.Migration):

    dependencies = [
        ("orchestra_ticketing", "0016_alter_onlineorder_marketing_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50, unique=True)),
                ("text", models.CharField(help_text="English text", max_length=200)),
                (
                    "translation",
                    models.CharField(help_text="Dutch translation", max_length=200),
                ),
            ],
        ),
        migrations.RunPython(
            migrate_marketing_choices, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="onlineorder",
            name="marketing_feedback",
            field=models.ForeignKey(
                blank=True,
                db_column="marketing_feedback",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orchestra_ticketing.marketingchoice",
                to_field="tag",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="marketing_choices",
            field=models.ManyToManyField(
                blank=True, to="orchestra_ticketing.marketingchoice"
            ),
        ),
        migrations.RunPython(
            assign_marketing_choices, migrations.RunPython.noop
        ),
    ]
