# Generated by Django 5.1.7 on 2026-10-05 12:13

from django.db import migrations, models


def preserve_extra_feedback_visibility(apps, schema_editor):
    MarketingChoice = apps.get_model("orchestra_ticketing", "MarketingChoice")
    MarketingChoice.objects.using(schema_editor.connection.alias).filter(
        tag__in=["andere", "muzikant", "dans_leuven", "dans_herent"]
    ).update(show_feedback_extra=True)


class Migration(migrations.Migration):

    dependencies = [
        ("orchestra_ticketing", "0017_dynamic_marketing_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingchoice",
            name="show_feedback_extra",
            field=models.BooleanField(
                default=False, verbose_name="Show extra feedback field"
            ),
        ),
        migrations.RunPython(
            preserve_extra_feedback_visibility, migrations.RunPython.noop
        ),
    ]
