# Generated by Django 4.2.2 on 2024-04-01 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('orchestra_ticketing', '0017_rename_pay_payment_id_onlineorder_pay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineorder',
            name='pay_order_id',
        ),
        migrations.RemoveField(
            model_name='onlineorder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='onlineorder',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
    ]
