# Generated by Django 5.0.3 on 2024-04-06 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orchestra_ticketing", "0018_remove_onlineorder_pay_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperorder",
            name="paid",
        ),
    ]
