# Generated by Django 5.0.3 on 2024-04-06 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orchestra_ticketing", "0019_rename_payed_order_paid_remove_paperorder_paid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payed",
            new_name="paid",
        ),
    ]
